Add endpoint to unsubscribe all users from a list
alphagov/email-alert-api pull request #1694
Opened 2022-01-06 15:49 UTC by barrucadu

We're going to use this with the single-page notifications feature to
alert a user when a page is removed or redirected, and remove their
now-dead current subscription.

I went back and forth on the naming for this a bit.  I originally used
"destroy", but actually we're not destroying the list here, we're just
unsubscribing everyone and (optionally) sending an email.  We could
destroy the list, but there isn't really any need to, as it'll be
cleared out by the HistoricDataDeletionWorker - and in fact I'm wary
of adding a new way of deleting data when there is already an
established pattern people may expect to hold.

So I went for "bulk-unsubscribe" instead.

2022-01-13 14:06 UTC, huwd approved these changes

2022-01-13 14:06 UTC, huwd commented
Looks good, pending: https://github.com/alphagov/email-alert-api/pull/1696

2022-01-13 17:54 UTC, huwd requested changes
Oh just realised are we missing this in /docs/api?

2022-01-14 09:57 UTC, barrucadu commented
Pushed two fixup commits where I've:

- Made it return a 202 (rather than a 204), to match the messages endpoint
- Rearranged the tests slightly so that message creation is tested regardless of whether or not there's a user
- Added the missing `GET /subscriber-lists/xxx` endpoint to the docs
- Added our new endpoint to the docs

2022-01-14 10:45 UTC, huwd approved these changes

2022-01-14 10:58 UTC, merged